#!/usr/bin/env python

import sys

from roslaunch_monitor.rqt_monitor_plugin import RQTMonitorPlugin
from rqt_gui.main import Main

plugin = 'RQTMonitorPlugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
